import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const currentPath = "/form";

    const excludeComponents = currentPath === "/form";

    return (
        <>
            {!excludeComponents && <Navbar />}
            <main>{children}</main>
            {!excludeComponents && <Footer />}
        </>
    );
}
